# Generated by Django 5.0.6 on 2024-05-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='product_store/images/category/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='product_store/images/product/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='product_store/images/subcategory/'),
        ),
    ]
