# Generated by Django 5.0.6 on 2024-05-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_large',
            field=models.ImageField(default=None, height_field=800, null=True, upload_to='product_store/images/product/', width_field=800),
        ),
        migrations.AddField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(default=None, height_field=500, null=True, upload_to='product_store/images/product/', width_field=500),
        ),
        migrations.AddField(
            model_name='product',
            name='image_small',
            field=models.ImageField(default=None, height_field=200, null=True, upload_to='product_store/images/product/', width_field=200),
        ),
    ]
