# Generated by Django 5.0.6 on 2024-05-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image_product_image_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_large',
            field=models.ImageField(default=None, null=True, upload_to='product_store/images/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(default=None, null=True, upload_to='product_store/images/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=models.ImageField(default=None, null=True, upload_to='product_store/images/product/'),
        ),
    ]
