# Generated by Django 5.0.6 on 2024-05-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cartedproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartedproduct',
            options={'verbose_name': 'Продукт в корзине', 'verbose_name_plural': 'Продукты в корзине'},
        ),
    ]
