# Generated by Django 5.0.6 on 2024-05-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_cartedproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='product_store/images/category/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_large',
            field=models.ImageField(default=None, null=True, upload_to='product_store/images/product/', verbose_name='Изображение большое'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(default=None, null=True, upload_to='product_store/images/product/', verbose_name='Изображение среднее'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=models.ImageField(default=None, null=True, upload_to='product_store/images/product/', verbose_name='Изображение маленькое'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='product_store/images/subcategory/', verbose_name='Изображение'),
        ),
    ]
